version: "3.5"
services:
  n1.example.net:
    container_name: n1
    image: nats
    dns_search: example.net
    entrypoint: /nats-server
    command: --name N1 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://n1:4245,nats://n2:4245 -p 4222
    networks:
    - nats
    ports:
    - 4222:4222

  n2.example.net:
    container_name: n2
    image: nats
    dns_search: example.net
    entrypoint: /nats-server
    command: --name N2 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://n1:4245,nats://n2:4245 -p 4222
    networks:
    - nats
    ports:
    - 4223:4222

networks:
  nats:
    name: nats